.text

        /* void add_naturals_aux(unsigned char* dst,
                                 unsigned char* src,
                                 int* carry);

        (1) The first and last sections of code simple create and destroy the
        stack frame.
        (2) Add the dst and src bytes 
        (3) Add in the carry argument
        Note: A new carry bit could be generated by either (2) or (3) but not
	both.  I'm using %cl to hold a cary from (2) and dl to hold carry from (3).
        (4) update the carry argument with the new carry status.
        */
        .global add_naturals_aux
add_naturals_aux:
        /* (1) */
        push  %ebp
        movl  %esp, %ebp

        /* (2) */
        movl  8(%ebp), %eax
        movl  12(%ebp), %ecx
        movb  (%ecx), %cl
        addb  %cl, (%eax)
        setc %cl

        /* (3) */
        movl  16(%ebp), %edx
        movl  (%edx), %edx
        addb  %dl, (%eax)
        setc  %dl

        /* (4) */
        orb  %dl, %cl
        movzbl %cl, %ecx
        movl  16(%ebp), %eax
        movl  %ecx, (%eax)

        /* (2) */
        leave
        ret
        
